name: Build-Test

on: [push]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pipenv
        make deps-install
    - name: Run lint
      run: |
        pipenv shell
        make lint
    - name: Run tests
      run: |
        pipenv shell
        make test
    - name: "Upload coverage to Codecov"
      if: github.repository == 'thingsapi/things-cli'
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
