name: Build-Test

on: [push]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        make deps-install
    - name: Run lint
      run: |
        pip install black pycodestyle pylama pylint flake8 mypy
        npm install -f pyright
        make lint
    - name: Run tests
      run: |
        pip install coverage
        make test
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
